import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./provider";
import { ThemeProvider } from "@/components/theme-provider";
import LayoutWrapper from "@/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Kratos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            {/* <Navbar /> */}
            <LayoutWrapper>{children}</LayoutWrapper>
            {/* <Navbar1 />
            <main>{children}</main>
            <Footer7 /> */}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
